[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
# Menandakan bahwa aplikasi ini memiliki antarmuka web yang dapat diakses publik
hc = { path = "/", status = 200 }