[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --chdir pv_monitoring app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
hc = { path = "/", status = 200 }